### ISSUE TITLE
Feature: Add WebSocket Client Support to Xojo iOS (Xojo.Net.TCPSocket)

### ISSUE THREAD

**Issue by sworteu** [ktekinay/Xojo-WebSocket#1]
I'd like to see Xojo.Net.TCPSocket to have WebSocket capabilities, Makes it super awsome to use Xojo iOS again!

**Comment by ktekinay** [comment]
The classes depend heavily on classic framework stuff like MemoryBlock and String, and that would have to be refactored too. This would become practical after Xojo moves to API 2.0 where those types and classes become universal.
